server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///Users/mourian-17388/Documents/Repo/config-repo
          default-label: master